//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperBloki.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constructors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constructors()
        {
            this.History_orders = new HashSet<History_orders>();
        }
    
        public int ConstructorID { get; set; }
        public int ConstructorNumber { get; set; }
        public string Name { get; set; }
        public string Series { get; set; }
        public string Producer { get; set; }
        public int ElementsAmount { get; set; }
        public decimal Priсe { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_orders> History_orders { get; set; }
    }
}
