//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperBloki.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_orders
    {
        public int id_client { get; set; }
        public int id_constructor { get; set; }
        public int id_worker { get; set; }
        public System.DateTime date_orders { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Constructors Constructors { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
